### ISSUE TITLE
"Only one instance of QtSESAM can run at a time."

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#82]
- Started a new Qt-Sesam.
- Could not decrypt my known password ( #57 ).
- Closed the Password dialog.
- Deleted the old ini file.
- Started Qt-Sesam again

message:
Only one instance of QtSESAM can run at a time.

There is no such task in the tasklist.

**Comment by Wikinaut** [comment]
related to #72 ?

**Comment by Wikinaut** [comment]
Not seen any more after a reboot.

**Comment by 607011** [comment]
It's intentional that "Only one instance of QtSESAM can run at a time." 

Qt-SESAM uses a [shared memory](http://doc.qt.io/qt-5/qsharedmemory.html) segment to determine whether or not another instance is running. Unfortunately, if Qt-SESAM crashes prematurely for some reason, this memory segment survives the crash on Linux, preventing further starts.

Solution: 
- Reboot (_Meh._)
- Start with `--force-start` command line switch (_Yeah!_)
